theme: jekyll-theme-cayman 
title: DanTDM Proxies
nav:
  - text: Laffyete
    url: //https:laffyete.industrialmill.com
  - text: Atlanta
    url: //https:atlanta.industrialmill.com/
  - text: Contact
    url: /contact
